m = input('Digite algo: ')
print (type(m))
print ('É numerico?', m.isnumeric())
print ('E alfanumnerico?', m.isalnum())
print ('É alfabetico? ', m.isalpha())
print ('É um espaço vazio?', m.isspace())
print ('É tudo maiusculo?', m.isupper())
print ('É tudo minusculo?', m.islower())
print ('Está capitalizado?', m.istitle())